parseModel, parseModelm and modelType: cleaned up the detection algorithm for whether a passed input is either a dQSSA model or an ode15s model.
odeKinetic: incorporated compartmentalised dQSSA for implicit complex concentrations. Also separated out and consolidated intrinsic model and tensors modified to passed parameter values (tensors modified by parameter values to be used by simulation are in model.run)

findTC: changed the flags which are identified as dQSSA models

odeQSSA: originally unmodified model (modelRaw) is what gets outputted by the program. Incorporated separation of parameter modified tensors. Also instantaneous spike of input no longer instantaneous. Has been taken out of original ramping phase and placed in the first 1e-6 portion of the actual simulation.

storeError: Fixed the indexing of error storage. Also changed the opening of text file to write permission rather than read and write.